"""Application-facing ports.

These are structural contracts only. Implementations belong to persistence,
provider, or platform adapter layers. No business logic is implemented here.
"""
from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID


class DecisionRepositoryPort(Protocol):
    def get_by_id(self, decision_id: str) -> Any: ...
    def create(self, decision_data: Any) -> Any: ...


class EvidenceRepositoryPort(Protocol):
    def get_by_id(self, evidence_id: str) -> Any: ...
    def create(
        self,
        *,
        source_type: str,
        raw_payload: Any,
        observed_at: Any,
        source_ref: str,
        collected_at: Any = None,
        collection_context: Any = None,
        evidence_id: UUID | None = None,
    ) -> Any: ...
    def soft_delete(self, evidence_id: str) -> Any: ...


class ExperimentRepositoryPort(Protocol):
    def get_by_id(self, experiment_id: str) -> Any: ...
    def create(self, experiment_data: Any) -> Any: ...
    def add_arm(self, experiment_id: str, arm_data: Any) -> Any: ...
    def get_arms(self, experiment_id: str) -> Any: ...


class PerformanceRepositoryPort(Protocol):
    def append(self, performance_snapshot: Any) -> Any: ...
    def get_by_id(self, performance_id: str) -> Any: ...
    def list_for_publication(self, publication_id: str) -> Any: ...


class LearningRepositoryPort(Protocol):
    def create(self, learning_data: Any) -> Any: ...
    def get_by_id(self, learning_id: str) -> Any: ...
    def add_provenance(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_provenance(self, *args: Any, **kwargs: Any) -> Any: ...
    def link_evidence(self, *args: Any, **kwargs: Any) -> Any: ...


class PublicationRepositoryPort(Protocol):
    """Persistence boundary for Publication; mutation semantics are TBD."""
    def create(self, publication_data: Any) -> Any: ...
    def get_by_id(self, publication_id: str) -> Any: ...


class ProviderPort(Protocol):
    def generate(self, request: Any) -> Any: ...


class PlatformAdapterPort(Protocol):
    def publish(self, request: Any) -> Any: ...
    def read_state(self, external_publication_id: str) -> Any: ...


class IdempotencyPort(Protocol):
    def resolve(self, intent_key: str) -> Any: ...
    def register(self, intent_key: str, publication_reference: Any) -> Any: ...


class ProvenancePort(Protocol):
    def record(self, event: Any) -> Any: ...


class ArtifactLineagePort(Protocol):
    def link(self, parent_reference: Any, child_reference: Any, relationship: str) -> Any: ...
